# Generated by Django 4.1 on 2022-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('stream', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=20)),
                ('classes_taught', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField()),
            ],
        ),
    ]
